AWSTemplateFormatVersion: '2010-09-09'
Description: Creates an S3 bucket with user-defined name, region, and versioning settings.
Outputs:
  BucketName:
    Description: Name of the created S3 bucket
    Value: ${BucketName}
Parameters:
  BucketName:
    Default: testbucketv11
    Description: Enter the name for the S3 bucket.
    Type: String
  Region:
    Default: us-west-2
    Description: Enter the AWS region (e.g., us-east-1, us-west-2).
    Type: String
  VersioningStatus:
    AllowedValues:
    - Enabled
    - Suspended
    Default: Suspended
    Description: Enable or disable versioning (Enabled/Disabled).
    Type: String
Resources:
  S3Bucket:
    Properties:
      BucketName: ${BucketName}
      VersioningConfiguration:
        Status: ${VersioningStatus}
    Type: AWS::S3::Bucket
