AWSTemplateFormatVersion: "2010-09-09"
Description: "Creates an S3 bucket with user-defined name, region, and versioning settings."

Parameters:
  BucketName:
    Type: String
    Description: "Enter the name for the S3 bucket."
    
  Region:
    Type: String
    Description: "Enter the AWS region (e.g., us-east-1, us-west-2)."

  VersioningStatus:
    Type: String
    Description: "Enable or disable versioning (Enabled/Disabled)."
    AllowedValues: 
      - "Enabled"
      - "Suspended"

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${BucketName}-${AWS::AccountId}"
      VersioningConfiguration:
        Status: !Ref VersioningStatus

Outputs:
  BucketName:
    Description: "Name of the created S3 bucket"
    Value: !Ref S3Bucket